name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.11.5
        job:
          - mypy .
          - black --check .
          - ruff check .
          - deptry .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: pip-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - run: poetry run ${{ matrix.job }}
